name: Build and Publish WASM

on:
  create:
    tags:
      - '*'

jobs:
  build-and-publish:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy, rust-src

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Build with wasm-pack
        run: wasm-pack build --target web .

      - name: Publish to npm
        run: |
          cd pkg
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          npm publish

